# version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 37017:27017
    volumes:
      - mongodb-data:/data/db

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chani-server
    ports:
      - 3001:3001
    depends_on:
      - redis
      - mongodb

volumes:
  redis-data:
    name: redis-data
    driver: local
  mongodb-data:
    name: mongodb-data
    driver: local
